apiVersion: v2
name: test-application
description: A Helm chart for Kubernetes to deploy the Test Application.
version: 1.0.0
appVersion: 1.0.0

keywords:
  - application
  - helm
  - kubernetes
sources:
  - https://github.com/killerclaws/DevOps-Project
maintainers:
  - name: Ankit Jaiswal
    email: ankit.aj9935@gmail.com

dependencies:
  - name: mysql
    version: 8.0.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled

# The Kubernetes version that this chart supports
kubeVersion: ">=1.16.0"

